import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');
const itemWidth = (width - 48) / 3; 

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#0084EC',
  },

  headerTopNav: {
    backgroundColor: '#0084EC',
    width: '100%',
    height: 65,
    justifyContent: 'center', 
    alignItems: 'center',
    position: 'relative',    
  },
  backButton: {
    position: 'absolute',   
    left: 16,                
    padding: 10,            
    zIndex: 10,             
  },
  logoContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
   logoImage: {
    width: 380,           
    height: 127,           
    resizeMode: 'contain',
    marginLeft: -10,
  },
  container: {
    flex: 1,
    backgroundColor: '#F4F7F6', 
    paddingHorizontal: 16,
  },
  bannerSpacer: {
    height: 15,
  },
  card: {
    backgroundColor: '#E11383', 
    borderRadius: 12,
    overflow: 'hidden',
    marginBottom: 24,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  cardTopSection: {
    padding: 18,
  },
  cardTitle: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '500',
    opacity: 0.95,
    marginBottom: 12,
  },
  saldoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  saldo: {
    color: '#FFFFFF',
    fontSize: 26,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  buttonRow: {
    flexDirection: 'row',
    backgroundColor: '#C2066D', 
    height: 48,
    alignItems: 'center',
  },
  miniButton: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
  },
  miniButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '500',
  },
  miniButtonDivider: {
    width: 1,
    height: '60%',
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#0076DF',
    marginBottom: 4,
  },
  sectionSubtitle: {
    fontSize: 14,
    color: '#1C69A7',
    fontWeight: '400',
    marginBottom: 16,
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    width: '100%',
  },
  gridItem: {
    backgroundColor: '#FFFFFF',
    width: itemWidth,
    height: itemWidth * 1.15,
    borderRadius: 10,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    justifyContent: 'flex-start',
  },
  iconContainer: {
    marginBottom: 12,
  },
  gridText: {
    fontSize: 13,
    color: '#2D3748',
    fontWeight: '600',
    lineHeight: 16,
  },
  helpCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 10,
    paddingHorizontal: 20,
    paddingVertical: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 12,
    width: '100%',
  },
  helpText: {
    color: '#0076DF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  avatarWrapper: {
    width: 42,
    height: 42,
    position: 'relative',
  },
  avatarCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#E2E8F0',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#CBD5E1',
  },
  whatsappBadge: {
    position: 'absolute',
    right: 0,
    top: 0,
    backgroundColor: '#25D366',
    width: 16,
    height: 16,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#FFFFFF',
  },
  tabBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 65,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    paddingBottom: 4,
  },
  tabItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  tabLabel: {
    fontSize: 10,
    color: '#7F8C8D',
    textAlign: 'center',
    marginTop: 2,
    lineHeight: 11,
  },
  tabLabelActive: {
    fontSize: 11,
    color: '#0084EC',
    fontWeight: 'bold',
    marginTop: 2,
  },
  tabActiveIndicator: {
    position: 'absolute',
    bottom: 2,
    width: 24,
    height: 3,
    backgroundColor: '#0084EC',
    borderRadius: 2,
  },
  tabCenterCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#E2E8F0',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: -4,
  },
});